/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coc;

import java.awt.Component;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author userpc
 */
public class SearchFrame extends javax.swing.JFrame {
    String[][] data;
    ResultSet res=null;
    Statement sttm;
    
    
    public SearchFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        searchID = new javax.swing.JComboBox();
        searchValue = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        traineeID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        mName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        sex = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        DOG = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        FOS = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        level = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        classification = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        aCenter = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tProvider = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        DOC = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1010, 474));
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabel1.setText("Search by:");

        searchID.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "First Name", "Middle Name", "Last Name", "ID" }));

        searchValue.setEditable(true);
        searchValue.setAutoscrolls(true);
        searchValue.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                searchValuePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        searchValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchValueActionPerformed(evt);
            }
        });

        jLabel2.setText("Value:");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Trainee detail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N
        jLayeredPane1.setMinimumSize(new java.awt.Dimension(712, 240));

        jPanel1.setMinimumSize(new java.awt.Dimension(350, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(350, 23));
        jPanel1.setLayout(new java.awt.GridLayout(0, 2, 5, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Trainee ID:");
        jPanel1.add(jLabel3);

        traineeID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        traineeID.setForeground(new java.awt.Color(0, 0, 255));
        jPanel1.add(traineeID);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("First Name:");
        jPanel1.add(jLabel4);

        fName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fName.setForeground(new java.awt.Color(0, 0, 255));
        jPanel1.add(fName);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Middle Name:");
        jLabel5.setMaximumSize(new java.awt.Dimension(55, 14));
        jLabel5.setMinimumSize(new java.awt.Dimension(55, 14));
        jPanel1.add(jLabel5);

        mName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mName.setForeground(new java.awt.Color(0, 0, 255));
        jPanel1.add(mName);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Last Name:");
        jPanel1.add(jLabel6);

        lName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lName.setForeground(new java.awt.Color(0, 0, 255));
        lName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNameActionPerformed(evt);
            }
        });
        jPanel1.add(lName);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Sex:");
        jLabel7.setMaximumSize(new java.awt.Dimension(55, 14));
        jLabel7.setMinimumSize(new java.awt.Dimension(55, 14));
        jPanel1.add(jLabel7);

        sex.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sex.setForeground(new java.awt.Color(0, 0, 255));
        jPanel1.add(sex);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Date of graduation:");
        jPanel1.add(jLabel9);

        DOG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DOG.setForeground(new java.awt.Color(0, 0, 255));
        jPanel1.add(DOG);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Field of study:");
        jLabel18.setToolTipText("");
        jPanel1.add(jLabel18);

        FOS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FOS.setForeground(new java.awt.Color(0, 0, 255));
        jPanel1.add(FOS);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Level:");
        jPanel1.add(jLabel13);

        level.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        level.setForeground(new java.awt.Color(0, 0, 255));
        jPanel1.add(level);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Class.:");
        jPanel1.add(jLabel14);

        classification.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        classification.setForeground(new java.awt.Color(0, 0, 255));
        jPanel1.add(classification);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Assess. center:");
        jLabel19.setToolTipText("");
        jPanel1.add(jLabel19);

        aCenter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        aCenter.setForeground(new java.awt.Color(0, 0, 255));
        jPanel1.add(aCenter);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Tr. provider:");
        jPanel1.add(jLabel20);

        tProvider.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tProvider.setForeground(new java.awt.Color(0, 0, 255));
        jPanel1.add(tProvider);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("DOC:");
        jPanel1.add(jLabel17);

        DOC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DOC.setForeground(new java.awt.Color(0, 0, 255));
        jPanel1.add(DOC);

        jPanel2.setMaximumSize(new java.awt.Dimension(240, 240));
        jPanel2.setMinimumSize(new java.awt.Dimension(240, 240));
        jPanel2.setPreferredSize(new java.awt.Dimension(240, 240));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coc/249967_181112005364823_1264962579_n.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
        );
        jLayeredPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setText("Pin Onboard");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Print");

        jButton3.setText("Done");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchValue, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchID, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(185, 185, 185))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton2, jButton3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(searchID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2, jButton3});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchValueActionPerformed
        // TODO add your handling code here:
        COC forSearch=new COC("");
         try 
         {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            forSearch.con = DriverManager.getConnection(forSearch.url, forSearch.username, forSearch.password);
            sttm = forSearch.con.createStatement(/*ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE*/);
            String SID=searchID.getSelectedItem().toString();
            String SV=searchValue.getSelectedItem().toString();
            if(searchID.getSelectedItem().toString().equalsIgnoreCase("ID"))
            {
                res = sttm.executeQuery("select *from trainee where TraineeID=\'" + SV + "\' ");
                displayResult(res);
            }
            else if(SID.equalsIgnoreCase("first name"))
            {
                res = sttm.executeQuery("select *from trainee where fName=\'" + SV + "\' ");
                int size=0;
                while (res.next()){size++;}
                res = sttm.executeQuery("select *from trainee where fName=\'" + SV + "\' ");
                data=new String[size][4];
                double[][][] numbers = new double[2][3][5];
                while (res.next()) 
                {
                    searchValue.removeAllItems();
                    for(int i=0;i<data.length;i++)
                    {
                        data[i][0]=res.getString("TraineeID");data[i][1]=res.getString("fName");data[i][2]=res.getString("mName");data[i][3]=res.getString("lName");
                        String temp=data[i][1]+" "+data[i][2]+" "+data[i][3];
                        searchValue.addItem((Object)temp);
                    }
                }
                SwingUtilities.invokeLater(new Runnable()
                {
                    public void run()
                    {
                        searchValue.setPopupVisible(true);
                    }
                });
                
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException ex) {
            JOptionPane.showConfirmDialog(null, ex.toString(), "url Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_searchValueActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        
    }//GEN-LAST:event_formKeyPressed

    private void searchValuePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_searchValuePopupMenuWillBecomeInvisible
        System.out.println("clicked");
        /*SwingUtilities.invokeLater(new Runnable()
        {
            public void run()
            {
                searchValue.setPopupVisible(false);
            }
        });*/
        System.out.println(searchValue.getItemCount());
        System.out.println(searchValue.getSelectedIndex());
        
    }//GEN-LAST:event_searchValuePopupMenuWillBecomeInvisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchFrame().setVisible(true);
                //JOptionPane.showMessageDialog(null, "testing...");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DOC;
    private javax.swing.JTextField DOG;
    private javax.swing.JTextField FOS;
    private javax.swing.JTextField aCenter;
    private javax.swing.JTextField classification;
    private javax.swing.JTextField fName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lName;
    private javax.swing.JTextField level;
    private javax.swing.JTextField mName;
    private javax.swing.JComboBox searchID;
    private javax.swing.JComboBox searchValue;
    private javax.swing.JTextField sex;
    private javax.swing.JTextField tProvider;
    private javax.swing.JTextField traineeID;
    // End of variables declaration//GEN-END:variables

    private void displayResult(ResultSet res) throws SQLException {
        while (res.next()) 
            {
                traineeID.setText(res.getString("traineeID"));
                fName.setText(res.getString("fName"));
                mName.setText(res.getString("mName"));
                lName.setText(res.getString("lName"));
                sex.setText(res.getString("sex"));
                DOG.setText(res.getString("D_O_G"));
                FOS.setText(res.getString("fieldOfStudy"));
                level.setText(res.getString("level"));
                classification.setText(res.getString("classification"));
                aCenter.setText(res.getString("assessmentCenter"));
                tProvider.setText(res.getString("trainingProvider"));                
                DOC.setText(res.getString("dateOfCompetation"));
            }
        }
}
